version: '3'

services:

  nginx:
    build:
      context: ./nginx
    ports:
        - "${HTTP_PORT}:80"
        - "${HTTPS_PORT}:443"
    volumes:
        - ${CODE_BASE_DIR}:/var/www
        
  php:
    build:
      context: ./php-fpm
      args:
        - PHP_VERSION=${PHP_VERSION}
    volumes:
        - ${CODE_BASE_DIR}:/var/www
        
  mysql:
    container_name: mysql
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${WORKSPACE_TIMEZONE}
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_PORT}:3306"
      
  redis:
    container_name: redis
    image: redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ${DATA_PATH_HOST}/redis:/data
      
  workspace:
    container_name: workspace
    build: 
      context: ./workspace
      args:
        - PHP_VERSION=${PHP_VERSION}
    ports:
      - "${SSH_PORT}:22"
    volumes:
      - ${CODE_BASE_DIR}:/var/www
    tty: true
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=${MYSQL_PORT}
    depends_on:
      - mysql
    restart: always
    ports:
     - "${PHPMYADMIN_PORT}:80"
    volumes:
     - /sessions