version: '3'

services:
  nginx:
    build:
      context: ./nginx
    ports:
        - "${HTTP_PORT}:80"
        - "${HTTPS_PORT}:443"
    volumes:
        - ${CODE_BASE_DIR}:/var/www
  php:
    build:
      context: ./php-fpm
      args:
        - PHP_VERSION=${PHP_VERSION}
    volumes:
        - ${CODE_BASE_DIR}:/var/www
  workspace:
    build: 
      context: ./workspace
      args:
        - PHP_VERSION=${PHP_VERSION}
    ports:
      - "${SSH_PORT}:22"
    volumes:
      - ${CODE_BASE_DIR}:/var/www
    tty: true
    